title: Capstone: ChatGPT, Numbers and The Meaning of Life 
author: JZstats
email: jzstats@yandex.com
description: This website showcases the project I produced for the Honors Track Assignment of the final Course 'Capstone; Retrieving, Processing and Visuallizing Data with Python' from 'Python for Everybody' Specialization by the 'University of Michigan' on Coursera.
github_username: jzstats

markdown: kramdown
theme: jekyll-theme-minimal

